version: 2

aliases:
  - &python_container
    - image: circleci/python:3.6.7

  - &install_pants
    name: Install pants and its dependencies
    command: |
      sudo apt-get update && sudo apt-get install -y curl gcc libffi-dev python2.7-dev default-jdk
      pip3 install setuptools
      curl -L -O https://pantsbuild.github.io/setup/pants && chmod +x pants
      ./pants -V

  - &pants_test
    name: Invoke pants testing
    command: |
      ./pants test test/$PROGLANG/$PROJECT_DIR

  - &pants_build_binary
    name: Invoke pants build
    command: |
      ./pants

  - &test_environment
    name: Spin up environment for testing and run tests
    docker: *python_container
    steps:
      - checkout
      - run: *install_pants
      - run: *pants_test

  - &build_environment
    name: Spin up environment for pants build
    docker: *python_container
    steps:
      - checkout
      - run: *install_pants
      - run: *pants_build_binary

jobs:
  test_api:
    <<: *test_environment
    name: Invoke tests on api
    working_directory: ~/drop_pants
    environment:
      PROJECT_DIR: api
      PROGLANG: python
      LANG: C.UTF-8

  test_app:
    <<: *test_environment
    name: Invoke tests on app
    working_directory: ~/drop_pants
    environment:
      PROJECT_DIR: app
      PROGLANG: python
      LANG: C.UTF-8

workflows:
  version: 2
  build:
    jobs:
      - test_api
      - test_app:
          requires:
            - test_api
