version: 2

aliases:
  - &python_container
    - image: circleci/python:3.6.7

  - &install_pants
    name: Install pants and its dependencies
    command: |
      sudo apt-get update && sudo apt-get install -y curl gcc libffi-dev python2.7-dev default-jdk
      pip3 install setuptools
      curl -L -O https://pantsbuild.github.io/setup/pants && chmod +x pants
      ./pants -V

  - &pants_test
    name: Invoke pants testing
    command: |
      TEST_FOLDERS=($(ls -d test/$PROGLANG/*/))
      for folder in "${TEST_FOLDERS[@]}"
      do
        ./pants test $folder:test
      done

  - &pants_build_binary
    name: Invoke pants build
    command: |
      ./pants

  - &test_environment
    name: Spin up environment for testing and run tests
    docker: *python_container
    steps:
      - checkout
      - run: *install_pants
      - run: *pants_test

  - &build_environment
    name: Spin up environment for pants build
    docker: *python_container
    steps:
      - checkout
      - run: *install_pants
      - run: *pants_build_binary

jobs:
  test_all:
    <<: *test_environment
    name: Invoke all tests described in test/python/BUILD
    working_directory: ~/drop_pants
    environment:
      PROGLANG: python
      LANG: C.UTF-8

workflows:
  version: 2
  build:
    jobs:
      - test_all
