python_tests(
  name = 'run_all_tests',
  dependencies=[
    '3rdparty/python:urllib3',
    'src/python/app/model',
    'src/python/app/view',
    'src/python/api',
    'test/python/app:test',
    'test/python/api:test'
  ]
)
